version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - ./src/main/resources/theme/:/opt/keycloak/themes/
    #  - ./target/scc-keycloak-theme.jar:/opt/keycloak/providers/scc-keycloak-theme.jar
    command: [ "start-dev" ]
