name: "Security Audit"

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: '54 3 * * 1'

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Verify Maven and Java
        run: |
          mvn --version

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'java'

      - name: Build package
        run: |
          mvn --quiet -B -U --fail-fast -DskipTests package

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
